deadstock/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls', namespace='stock')),
]

stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'

urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path('', views.InventoryListView.as_view(), name='inventory_lists'),
    path('<int:Sr_no>/<Dsr_no>/<Voucher_no>/<Recipt_date>/',views.inventory_detail,name='inventory_detail'),
    path('search/', views.post_search, name='post_search'),

    
]

stock/models.py
from pickle import TRUE
from django.db import models
from django.urls import reverse
# Create your models here.

class inventory(models.Model):
   
    Sr_no = models.AutoField(primary_key=True)
    Dsr_no = models.CharField(max_length=250)
    Voucher_no = models.CharField(max_length=250)
    Recipt_date = models.DateField()
    supplier_name_adress = models.CharField(max_length=500)
    rv_no = models.CharField(max_length=250)
    name = models.CharField(max_length=250)
    qty_recived = models.IntegerField()
    qty_issued = models.IntegerField()
    qty_balanced = models.IntegerField()
    cost = models.IntegerField()
    current_locaton = models.CharField(max_length=20)
    depriciation_cost = models.IntegerField()
    def get_absolute_url(self):
        return reverse('stock:inventory_detail',
                       args=[self.Sr_no,
                             self.Dsr_no,
                             self.Voucher_no,
                             self.Recipt_date])

stock/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()

stock/views.py
import imp
from django.shortcuts import render
from numpy import rec
from .models import inventory
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger

from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.contrib.postgres.search import SearchVector
from .forms import  SearchForm
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = inventory.objects.annotate(
                search=SearchVector('rv_no','current_locaton'),
            ).filter(search=query)
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

# Cre ate your views here.
def inventory_lists(request):
    object_list = inventory.objects.all()
    paginator = Paginator(object_list, 5) # 3 posts in each page
    page = request.GET.get('page')
    try:
        Inventory = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        Inventory = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        Inventory = paginator.page(paginator.num_pages)
    return render(request,
                 'blog/post/list.html',
                 {'page': page,
                  'inventory': Inventory})


def inventory_detail(request):
     invo = get_object_or_404(inventory ,name = 'name',rv_no = 'rv_no')
     
     return render(request,
                  'blog/post/detail.html',
                  {'invo': invo})


def inventory_detail(request,Sr_no ,Dsr_no,Voucher_no,Recipt_date):
    post = get_object_or_404(inventory, Sr_no = Sr_no,Dsr_no=Dsr_no,Voucher_no=Voucher_no,Recipt_date= Recipt_date)
    return render(request,
                  'blog/post/detail.html',
                  {'post': post})

class InventoryListView(ListView):
    queryset = inventory.objects.all()
    context_object_name = 'inventory'
    paginate_by = 5
    template_name = 'blog/post/list.html'

stock/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My Inventory</h2>
    
  </div>
</body>
</html>

stock/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ invo.name }}{% endblock %}

{% block content %}
<h1>{{post.name}}</h1>
<p>
   rv_no {{post.rv_no}}
   Voucher_no{{post.Voucher_no}}
</p>
{% endblock %}

stock/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Inventory{% endblock %}

{% block content %}
  <h1>Inventory</h1>
  {% for x in inventory %}
 
    <h2>
        {{x.Sr_no }} |  <a href="{{ x.get_absolute_url }}">
          {{ x.name }}
        </a> |rv_no -{{x.rv_no}}
      </a>
    </h2>
    <p > 
      location: {{ x.current_locaton }}
    </p>
    {{ x.location|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=page_obj %}
{% endblock %}

stock/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>stock in  "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.name }}</a></h4>
        
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "stock:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for stock</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

stock/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>